name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create zip
        run: |
          cd custom_components/amber_sigen_sync
          zip -r ../../amber_sigen_sync.zip .

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: amber_sigen_sync.zip
